// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: curve_point.proto

#ifndef PROTOBUF_INCLUDED_curve_5fpoint_2eproto
#define PROTOBUF_INCLUDED_curve_5fpoint_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3007000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3007001 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_curve_5fpoint_2eproto

// Internal implementation detail -- do not use these members.
struct TableStruct_curve_5fpoint_2eproto {
  static const ::google::protobuf::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::google::protobuf::internal::ParseTable schema[1]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors_curve_5fpoint_2eproto();
namespace safeheron {
namespace proto {
class CurvePoint;
class CurvePointDefaultTypeInternal;
extern CurvePointDefaultTypeInternal _CurvePoint_default_instance_;
}  // namespace proto
}  // namespace safeheron
namespace google {
namespace protobuf {
template<> ::safeheron::proto::CurvePoint* Arena::CreateMaybeMessage<::safeheron::proto::CurvePoint>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace safeheron {
namespace proto {

// ===================================================================

class CurvePoint :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:safeheron.proto.CurvePoint) */ {
 public:
  CurvePoint();
  virtual ~CurvePoint();

  CurvePoint(const CurvePoint& from);

  inline CurvePoint& operator=(const CurvePoint& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  CurvePoint(CurvePoint&& from) noexcept
    : CurvePoint() {
    *this = ::std::move(from);
  }

  inline CurvePoint& operator=(CurvePoint&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor() {
    return default_instance().GetDescriptor();
  }
  static const CurvePoint& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const CurvePoint* internal_default_instance() {
    return reinterpret_cast<const CurvePoint*>(
               &_CurvePoint_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(CurvePoint* other);
  friend void swap(CurvePoint& a, CurvePoint& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline CurvePoint* New() const final {
    return CreateMaybeMessage<CurvePoint>(nullptr);
  }

  CurvePoint* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<CurvePoint>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const CurvePoint& from);
  void MergeFrom(const CurvePoint& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
  ::google::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(CurvePoint* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string x = 1;
  void clear_x();
  static const int kXFieldNumber = 1;
  const ::std::string& x() const;
  void set_x(const ::std::string& value);
  #if LANG_CXX11
  void set_x(::std::string&& value);
  #endif
  void set_x(const char* value);
  void set_x(const char* value, size_t size);
  ::std::string* mutable_x();
  ::std::string* release_x();
  void set_allocated_x(::std::string* x);

  // string y = 2;
  void clear_y();
  static const int kYFieldNumber = 2;
  const ::std::string& y() const;
  void set_y(const ::std::string& value);
  #if LANG_CXX11
  void set_y(::std::string&& value);
  #endif
  void set_y(const char* value);
  void set_y(const char* value, size_t size);
  ::std::string* mutable_y();
  ::std::string* release_y();
  void set_allocated_y(::std::string* y);

  // string curve = 3;
  void clear_curve();
  static const int kCurveFieldNumber = 3;
  const ::std::string& curve() const;
  void set_curve(const ::std::string& value);
  #if LANG_CXX11
  void set_curve(::std::string&& value);
  #endif
  void set_curve(const char* value);
  void set_curve(const char* value, size_t size);
  ::std::string* mutable_curve();
  ::std::string* release_curve();
  void set_allocated_curve(::std::string* curve);

  // @@protoc_insertion_point(class_scope:safeheron.proto.CurvePoint)
 private:
  class HasBitSetters;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr x_;
  ::google::protobuf::internal::ArenaStringPtr y_;
  ::google::protobuf::internal::ArenaStringPtr curve_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_curve_5fpoint_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// CurvePoint

// string x = 1;
inline void CurvePoint::clear_x() {
  x_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& CurvePoint::x() const {
  // @@protoc_insertion_point(field_get:safeheron.proto.CurvePoint.x)
  return x_.GetNoArena();
}
inline void CurvePoint::set_x(const ::std::string& value) {
  
  x_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:safeheron.proto.CurvePoint.x)
}
#if LANG_CXX11
inline void CurvePoint::set_x(::std::string&& value) {
  
  x_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:safeheron.proto.CurvePoint.x)
}
#endif
inline void CurvePoint::set_x(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  x_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:safeheron.proto.CurvePoint.x)
}
inline void CurvePoint::set_x(const char* value, size_t size) {
  
  x_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:safeheron.proto.CurvePoint.x)
}
inline ::std::string* CurvePoint::mutable_x() {
  
  // @@protoc_insertion_point(field_mutable:safeheron.proto.CurvePoint.x)
  return x_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* CurvePoint::release_x() {
  // @@protoc_insertion_point(field_release:safeheron.proto.CurvePoint.x)
  
  return x_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void CurvePoint::set_allocated_x(::std::string* x) {
  if (x != nullptr) {
    
  } else {
    
  }
  x_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), x);
  // @@protoc_insertion_point(field_set_allocated:safeheron.proto.CurvePoint.x)
}

// string y = 2;
inline void CurvePoint::clear_y() {
  y_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& CurvePoint::y() const {
  // @@protoc_insertion_point(field_get:safeheron.proto.CurvePoint.y)
  return y_.GetNoArena();
}
inline void CurvePoint::set_y(const ::std::string& value) {
  
  y_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:safeheron.proto.CurvePoint.y)
}
#if LANG_CXX11
inline void CurvePoint::set_y(::std::string&& value) {
  
  y_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:safeheron.proto.CurvePoint.y)
}
#endif
inline void CurvePoint::set_y(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  y_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:safeheron.proto.CurvePoint.y)
}
inline void CurvePoint::set_y(const char* value, size_t size) {
  
  y_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:safeheron.proto.CurvePoint.y)
}
inline ::std::string* CurvePoint::mutable_y() {
  
  // @@protoc_insertion_point(field_mutable:safeheron.proto.CurvePoint.y)
  return y_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* CurvePoint::release_y() {
  // @@protoc_insertion_point(field_release:safeheron.proto.CurvePoint.y)
  
  return y_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void CurvePoint::set_allocated_y(::std::string* y) {
  if (y != nullptr) {
    
  } else {
    
  }
  y_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), y);
  // @@protoc_insertion_point(field_set_allocated:safeheron.proto.CurvePoint.y)
}

// string curve = 3;
inline void CurvePoint::clear_curve() {
  curve_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& CurvePoint::curve() const {
  // @@protoc_insertion_point(field_get:safeheron.proto.CurvePoint.curve)
  return curve_.GetNoArena();
}
inline void CurvePoint::set_curve(const ::std::string& value) {
  
  curve_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:safeheron.proto.CurvePoint.curve)
}
#if LANG_CXX11
inline void CurvePoint::set_curve(::std::string&& value) {
  
  curve_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:safeheron.proto.CurvePoint.curve)
}
#endif
inline void CurvePoint::set_curve(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  curve_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:safeheron.proto.CurvePoint.curve)
}
inline void CurvePoint::set_curve(const char* value, size_t size) {
  
  curve_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:safeheron.proto.CurvePoint.curve)
}
inline ::std::string* CurvePoint::mutable_curve() {
  
  // @@protoc_insertion_point(field_mutable:safeheron.proto.CurvePoint.curve)
  return curve_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* CurvePoint::release_curve() {
  // @@protoc_insertion_point(field_release:safeheron.proto.CurvePoint.curve)
  
  return curve_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void CurvePoint::set_allocated_curve(::std::string* curve) {
  if (curve != nullptr) {
    
  } else {
    
  }
  curve_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), curve);
  // @@protoc_insertion_point(field_set_allocated:safeheron.proto.CurvePoint.curve)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace proto
}  // namespace safeheron

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // PROTOBUF_INCLUDED_curve_5fpoint_2eproto
