// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: curve_point.proto

#include "curve_point.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

namespace safeheron {
namespace proto {
class CurvePointDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<CurvePoint> _instance;
} _CurvePoint_default_instance_;
}  // namespace proto
}  // namespace safeheron
static void InitDefaultsCurvePoint_curve_5fpoint_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::safeheron::proto::_CurvePoint_default_instance_;
    new (ptr) ::safeheron::proto::CurvePoint();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::safeheron::proto::CurvePoint::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_CurvePoint_curve_5fpoint_2eproto =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsCurvePoint_curve_5fpoint_2eproto}, {}};

void InitDefaults_curve_5fpoint_2eproto() {
  ::google::protobuf::internal::InitSCC(&scc_info_CurvePoint_curve_5fpoint_2eproto.base);
}

::google::protobuf::Metadata file_level_metadata_curve_5fpoint_2eproto[1];
constexpr ::google::protobuf::EnumDescriptor const** file_level_enum_descriptors_curve_5fpoint_2eproto = nullptr;
constexpr ::google::protobuf::ServiceDescriptor const** file_level_service_descriptors_curve_5fpoint_2eproto = nullptr;

const ::google::protobuf::uint32 TableStruct_curve_5fpoint_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::safeheron::proto::CurvePoint, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::safeheron::proto::CurvePoint, x_),
  PROTOBUF_FIELD_OFFSET(::safeheron::proto::CurvePoint, y_),
  PROTOBUF_FIELD_OFFSET(::safeheron::proto::CurvePoint, curve_),
};
static const ::google::protobuf::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::safeheron::proto::CurvePoint)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::safeheron::proto::_CurvePoint_default_instance_),
};

::google::protobuf::internal::AssignDescriptorsTable assign_descriptors_table_curve_5fpoint_2eproto = {
  {}, AddDescriptors_curve_5fpoint_2eproto, "curve_point.proto", schemas,
  file_default_instances, TableStruct_curve_5fpoint_2eproto::offsets,
  file_level_metadata_curve_5fpoint_2eproto, 1, file_level_enum_descriptors_curve_5fpoint_2eproto, file_level_service_descriptors_curve_5fpoint_2eproto,
};

const char descriptor_table_protodef_curve_5fpoint_2eproto[] =
  "\n\021curve_point.proto\022\017safeheron.proto\"1\n\n"
  "CurvePoint\022\t\n\001x\030\001 \001(\t\022\t\n\001y\030\002 \001(\t\022\r\n\005curv"
  "e\030\003 \001(\tb\006proto3"
  ;
::google::protobuf::internal::DescriptorTable descriptor_table_curve_5fpoint_2eproto = {
  false, InitDefaults_curve_5fpoint_2eproto, 
  descriptor_table_protodef_curve_5fpoint_2eproto,
  "curve_point.proto", &assign_descriptors_table_curve_5fpoint_2eproto, 95,
};

void AddDescriptors_curve_5fpoint_2eproto() {
  static constexpr ::google::protobuf::internal::InitFunc deps[1] =
  {
  };
 ::google::protobuf::internal::AddDescriptors(&descriptor_table_curve_5fpoint_2eproto, deps, 0);
}

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_curve_5fpoint_2eproto = []() { AddDescriptors_curve_5fpoint_2eproto(); return true; }();
namespace safeheron {
namespace proto {

// ===================================================================

void CurvePoint::InitAsDefaultInstance() {
}
class CurvePoint::HasBitSetters {
 public:
};

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int CurvePoint::kXFieldNumber;
const int CurvePoint::kYFieldNumber;
const int CurvePoint::kCurveFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

CurvePoint::CurvePoint()
  : ::google::protobuf::Message(), _internal_metadata_(nullptr) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:safeheron.proto.CurvePoint)
}
CurvePoint::CurvePoint(const CurvePoint& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(nullptr) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  x_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.x().size() > 0) {
    x_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.x_);
  }
  y_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.y().size() > 0) {
    y_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.y_);
  }
  curve_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.curve().size() > 0) {
    curve_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.curve_);
  }
  // @@protoc_insertion_point(copy_constructor:safeheron.proto.CurvePoint)
}

void CurvePoint::SharedCtor() {
  ::google::protobuf::internal::InitSCC(
      &scc_info_CurvePoint_curve_5fpoint_2eproto.base);
  x_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  y_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  curve_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

CurvePoint::~CurvePoint() {
  // @@protoc_insertion_point(destructor:safeheron.proto.CurvePoint)
  SharedDtor();
}

void CurvePoint::SharedDtor() {
  x_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  y_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  curve_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void CurvePoint::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const CurvePoint& CurvePoint::default_instance() {
  ::google::protobuf::internal::InitSCC(&::scc_info_CurvePoint_curve_5fpoint_2eproto.base);
  return *internal_default_instance();
}


void CurvePoint::Clear() {
// @@protoc_insertion_point(message_clear_start:safeheron.proto.CurvePoint)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  x_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  y_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  curve_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  _internal_metadata_.Clear();
}

#if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
const char* CurvePoint::_InternalParse(const char* begin, const char* end, void* object,
                  ::google::protobuf::internal::ParseContext* ctx) {
  auto msg = static_cast<CurvePoint*>(object);
  ::google::protobuf::int32 size; (void)size;
  int depth; (void)depth;
  ::google::protobuf::uint32 tag;
  ::google::protobuf::internal::ParseFunc parser_till_end; (void)parser_till_end;
  auto ptr = begin;
  while (ptr < end) {
    ptr = ::google::protobuf::io::Parse32(ptr, &tag);
    GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
    switch (tag >> 3) {
      // string x = 1;
      case 1: {
        if (static_cast<::google::protobuf::uint8>(tag) != 10) goto handle_unusual;
        ptr = ::google::protobuf::io::ReadSize(ptr, &size);
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        ctx->extra_parse_data().SetFieldName("safeheron.proto.CurvePoint.x");
        object = msg->mutable_x();
        if (size > end - ptr + ::google::protobuf::internal::ParseContext::kSlopBytes) {
          parser_till_end = ::google::protobuf::internal::GreedyStringParserUTF8;
          goto string_till_end;
        }
        GOOGLE_PROTOBUF_PARSER_ASSERT(::google::protobuf::internal::StringCheckUTF8(ptr, size, ctx));
        ::google::protobuf::internal::InlineGreedyStringParser(object, ptr, size, ctx);
        ptr += size;
        break;
      }
      // string y = 2;
      case 2: {
        if (static_cast<::google::protobuf::uint8>(tag) != 18) goto handle_unusual;
        ptr = ::google::protobuf::io::ReadSize(ptr, &size);
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        ctx->extra_parse_data().SetFieldName("safeheron.proto.CurvePoint.y");
        object = msg->mutable_y();
        if (size > end - ptr + ::google::protobuf::internal::ParseContext::kSlopBytes) {
          parser_till_end = ::google::protobuf::internal::GreedyStringParserUTF8;
          goto string_till_end;
        }
        GOOGLE_PROTOBUF_PARSER_ASSERT(::google::protobuf::internal::StringCheckUTF8(ptr, size, ctx));
        ::google::protobuf::internal::InlineGreedyStringParser(object, ptr, size, ctx);
        ptr += size;
        break;
      }
      // string curve = 3;
      case 3: {
        if (static_cast<::google::protobuf::uint8>(tag) != 26) goto handle_unusual;
        ptr = ::google::protobuf::io::ReadSize(ptr, &size);
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        ctx->extra_parse_data().SetFieldName("safeheron.proto.CurvePoint.curve");
        object = msg->mutable_curve();
        if (size > end - ptr + ::google::protobuf::internal::ParseContext::kSlopBytes) {
          parser_till_end = ::google::protobuf::internal::GreedyStringParserUTF8;
          goto string_till_end;
        }
        GOOGLE_PROTOBUF_PARSER_ASSERT(::google::protobuf::internal::StringCheckUTF8(ptr, size, ctx));
        ::google::protobuf::internal::InlineGreedyStringParser(object, ptr, size, ctx);
        ptr += size;
        break;
      }
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->EndGroup(tag);
          return ptr;
        }
        auto res = UnknownFieldParse(tag, {_InternalParse, msg},
          ptr, end, msg->_internal_metadata_.mutable_unknown_fields(), ctx);
        ptr = res.first;
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr != nullptr);
        if (res.second) return ptr;
      }
    }  // switch
  }  // while
  return ptr;
string_till_end:
  static_cast<::std::string*>(object)->clear();
  static_cast<::std::string*>(object)->reserve(size);
  goto len_delim_till_end;
len_delim_till_end:
  return ctx->StoreAndTailCall(ptr, end, {_InternalParse, msg},
                               {parser_till_end, object}, size);
}
#else  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
bool CurvePoint::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!PROTOBUF_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:safeheron.proto.CurvePoint)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // string x = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (10 & 0xFF)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_x()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->x().data(), static_cast<int>(this->x().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "safeheron.proto.CurvePoint.x"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string y = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (18 & 0xFF)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_y()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->y().data(), static_cast<int>(this->y().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "safeheron.proto.CurvePoint.y"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string curve = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (26 & 0xFF)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_curve()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->curve().data(), static_cast<int>(this->curve().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "safeheron.proto.CurvePoint.curve"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:safeheron.proto.CurvePoint)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:safeheron.proto.CurvePoint)
  return false;
#undef DO_
}
#endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER

void CurvePoint::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:safeheron.proto.CurvePoint)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string x = 1;
  if (this->x().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->x().data(), static_cast<int>(this->x().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "safeheron.proto.CurvePoint.x");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->x(), output);
  }

  // string y = 2;
  if (this->y().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->y().data(), static_cast<int>(this->y().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "safeheron.proto.CurvePoint.y");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->y(), output);
  }

  // string curve = 3;
  if (this->curve().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->curve().data(), static_cast<int>(this->curve().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "safeheron.proto.CurvePoint.curve");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      3, this->curve(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:safeheron.proto.CurvePoint)
}

::google::protobuf::uint8* CurvePoint::InternalSerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:safeheron.proto.CurvePoint)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string x = 1;
  if (this->x().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->x().data(), static_cast<int>(this->x().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "safeheron.proto.CurvePoint.x");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->x(), target);
  }

  // string y = 2;
  if (this->y().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->y().data(), static_cast<int>(this->y().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "safeheron.proto.CurvePoint.y");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->y(), target);
  }

  // string curve = 3;
  if (this->curve().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->curve().data(), static_cast<int>(this->curve().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "safeheron.proto.CurvePoint.curve");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        3, this->curve(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:safeheron.proto.CurvePoint)
  return target;
}

size_t CurvePoint::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:safeheron.proto.CurvePoint)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string x = 1;
  if (this->x().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->x());
  }

  // string y = 2;
  if (this->y().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->y());
  }

  // string curve = 3;
  if (this->curve().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->curve());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void CurvePoint::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:safeheron.proto.CurvePoint)
  GOOGLE_DCHECK_NE(&from, this);
  const CurvePoint* source =
      ::google::protobuf::DynamicCastToGenerated<CurvePoint>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:safeheron.proto.CurvePoint)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:safeheron.proto.CurvePoint)
    MergeFrom(*source);
  }
}

void CurvePoint::MergeFrom(const CurvePoint& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:safeheron.proto.CurvePoint)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.x().size() > 0) {

    x_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.x_);
  }
  if (from.y().size() > 0) {

    y_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.y_);
  }
  if (from.curve().size() > 0) {

    curve_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.curve_);
  }
}

void CurvePoint::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:safeheron.proto.CurvePoint)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void CurvePoint::CopyFrom(const CurvePoint& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:safeheron.proto.CurvePoint)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool CurvePoint::IsInitialized() const {
  return true;
}

void CurvePoint::Swap(CurvePoint* other) {
  if (other == this) return;
  InternalSwap(other);
}
void CurvePoint::InternalSwap(CurvePoint* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
  x_.Swap(&other->x_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  y_.Swap(&other->y_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  curve_.Swap(&other->curve_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
}

::google::protobuf::Metadata CurvePoint::GetMetadata() const {
  ::google::protobuf::internal::AssignDescriptors(&::assign_descriptors_table_curve_5fpoint_2eproto);
  return ::file_level_metadata_curve_5fpoint_2eproto[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace proto
}  // namespace safeheron
namespace google {
namespace protobuf {
template<> PROTOBUF_NOINLINE ::safeheron::proto::CurvePoint* Arena::CreateMaybeMessage< ::safeheron::proto::CurvePoint >(Arena* arena) {
  return Arena::CreateInternal< ::safeheron::proto::CurvePoint >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
